[window]
dimensions = { columns = 118, lines = 30}
padding = { x = 2, y = 0}
dynamic_padding = true
opacity = 0.5
blur = true

[font]
normal = { family = "Monospace", style = "Regular"}
bold = { family = "Monospace", style = "Bold" }
italic = { family = "Monospace", style = "Italic" }
bold_italic = { family = "Monospace", style = "Bold Italic" }
size = 12

[colors.primary]
background = "#303446"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }

[general]
import = [
    "~/.config/alacritty/github.toml"
    #"~/.config/alacritty/catppuccin-frappe.toml"
]

[terminal]
shell = { program = "/bin/fish",  args = ["-l"] }
osc52 = "CopyPaste"
