Host aur.archlinux.org
  User aur
  IdentityFile ~/.ssh/aur

Host github.com
  HostName ssh.github.com
  Port 443
  User git
  IdentityFile ~/.ssh/github

Host gitlab.winehq.org
  HostName gitlab.winehq.org
  IdentityFile ~/.ssh/winehq
