MBTN_LEFT               ignore
MBTN_LEFT_DBL           cycle pause
MBTN_RIGHT              script-binding playlist_osd/display
WHEEL_UP                add volume 5
WHEEL_DOWN              add volume -5
MBTN_LEFT_DBL           cycle pause

RIGHT                   seek  5
Shift+RIGHT             seek  1 exact
LEFT                    seek -5
Shift+LEFT              seek -1 exact
UP                      add volume 5
DOWN                    add volume  -5
b                       add sub-delay -0.05
n                       add sub-delay +0.05

m                       cycle mute
f                       cycle fullscreen
ESC                     set fullscreen no
SPACE                   cycle pause
z                       add speed -0.5
x                       set speed 1.0
c                       add speed  0.5
Ctrl+q                  quit
TAB                     script-binding stats/display-stats-toggle
Ctrl+s                  screenshot video
Ctrl+Shift+s            screenshot
