############
# 基础配置 #
############
#vo = dmabuf-wayland

hwdec = auto
hwdec-codecs = all
input-builtin-bindings = no
osc = no
osd-on-seek = no
hr-seek-framedrop = no
# 自动下一集与结束后暂停冲突
# autocreate-playlist = same
keep-open = yes

########
# 视频 #
########
# 降低内容与屏幕帧率不匹配带来的卡顿感
video-sync = display-resample
tscale = oversample
interpolation = yes

########
# 音频 #
########
volume = 100
audio-file-auto = fuzzy

########
# 字幕 #
########
sub-auto = fuzzy
blend-subtitles = video
sub-font = "sans-serif"

########
# 截图 #
########
screenshot-format = jxl
screenshot-template = "~/Pictures/ScreenShots/mpv/mpv_screenshot-%tY%tm%td_%tH:%tM:%tS"

########
# 在线 #
########
demuxer-hysteresis-secs = 10
